services:
  movie_app:
    image: movie_app_backend
    container_name: movie_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/movies_app
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: 123456

      ##MailConfiguration
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: alaaapu135@gmail.com
      SPRING_MAIL_PASSWORD: tcjtoqxzutpbvhma
      SPRING_MAIL_PROPERTIES_MAIL__SMTP__AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL__SMTP__STARTTLS__ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL__SMTP__STARTTLS__REQUIRED: "true"
      SPRING_MAIL_PROPERTIES_MAIL__SMTP__SSL__TRUST: smtp.gmail.com

    networks:
      - aabouelsoud
    volumes:
      - "${HOME}/.systemproperties:/root/"
      - "${USERPROFILE}/.systemproperties:/root/"


networks:
  aabouelsoud:
    external: true