version: "3.9"  # Docker Compose file format version

services:
  db:
    image: postgres
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hggi
      POSTGRES_DB: movie_app
    networks:
      - aabouelsoud
    healthcheck:                     # Ensures DB is ready before app starts
      test: ["CMD-SHELL","pg_isready -U postgres -d movie_app"]
      interval: 10s                  # Run check every 10 seconds
      timeout: 5s                    # Fail if check takes more than 5s
      retries: 5                     # Try 5 times before marking as unhealthy
    volumes:
      - postgres_data:/var/lib/postgresql/data


  movie_app:
    image: movie_app_backend                # App image (built from Dockerfile)
    container_name: movie-app-container

    build:                                  # Build context for the app
      context: .                            # Current directory
      dockerfile: Dockerfile                # Use specified Dockerfile

    restart: on-failure                     # Restart app if it crashes

    ports:
      - "5055:5055"

    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}

    depends_on:
      db:
        condition: service_healthy          # Wait until DB health check passes

    networks:
      - aabouelsoud                         # Same network as DB for comms


networks:
  aabouelsoud:
    external: true


##Use service name (db) → when both DB and app run as Docker services in the same network.
#Use localhost:hostPort (localhost:5433) → when the app runs locally outside Docker.
#Never use the container name (postgres-db-container) in JDBC URL.