services:
  movie_app:
    image: movie_app_backend
    container_name: movie_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"

    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}

    networks:
      - aabouelsoud

networks:
  aabouelsoud:
    external: true