spring.application.name=MoviesApp
spring.main.banner-mode=console
server.port=5055
server.servlet.context-path=/rest
spring.messages.basename=messages
app.page.size=20
spring.main.allow-bean-definition-overriding=true

############### Datasource Configuration ###################
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/movie_app
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

############### Hibernate & JPA Configuration ###################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
############### Redis Configuration ###################
# Standard Standalone Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=2000ms
#spring.data.redis.url=redis://localhost:6379

app.admin.email=admin@gmail.com
app.admin.password=${ADMIN_PASSWORD}
############### JWT ###################
app.security.jwt.expiration=86400000
app.security.jwt.issuer=app.iss
#app.security.jwt.expiration=60000

############### Integration Configuration ###################
app.omdb.api.integration.key=f24617b3
app.omdb.base-url=https://www.omdbapi.com/?type=movie&apikey=

############### Mail Configuration ###################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.username=alaaapu135@gmail.com
spring.mail.password=${MAIL_PASSWORD}

#EmailTemplates
app.template.Account.Verification=src/main/resources/templates/AppEmailTemplate.html

##URLS
app.verification.verify-url=http://localhost:5055/rest/users/verify/account/