CREATE SEQUENCE user_pk_sequence
    START WITH 100
    INCREMENT BY 1;

CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      role_name VARCHAR(50) NOT NULL,
                      created_by_id BIGINT,
                      created_at TIMESTAMP WITH TIME ZONE,
                      last_modified_id BIGINT,
                      last_modified_at TIMESTAMP WITH TIME ZONE,
                      deleted_by_id BIGINT,
                      deleted_at TIMESTAMP WITH TIME ZONE,
                      CONSTRAINT pk_role PRIMARY KEY (id),
                      CONSTRAINT uk_role_role_name UNIQUE (role_name)
);


CREATE TABLE users (
                       id BIGINT NOT NULL,
                       first_name VARCHAR(50) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       username VARCHAR(50) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       type VARCHAR(50) NOT NULL,
                       salt_password VARCHAR(50) NOT NULL,
                       verification_code VARCHAR(50),
                       verification_code_expiry_date TIMESTAMP WITHOUT TIME ZONE,
                       is_verified BOOLEAN,
                       is_deleted BOOLEAN,
                       created_by_id BIGINT,
                       created_at TIMESTAMP WITH TIME ZONE,
                       last_modified_id BIGINT,
                       last_modified_at TIMESTAMP WITH TIME ZONE,
                       deleted_by_id BIGINT,
                       deleted_at TIMESTAMP WITH TIME ZONE,
                       role_id BIGINT NOT NULL,

                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uk_users_username UNIQUE (username),
                       CONSTRAINT uk_users_email UNIQUE (email),

                       CONSTRAINT fk_users_role
                           FOREIGN KEY (role_id)
                               REFERENCES role(id)
);

CREATE TABLE movie (
                       movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       imdbid VARCHAR(255) NOT NULL,
                       title VARCHAR(255) NOT NULL,
                       year VARCHAR(255) NOT NULL,
                       rated VARCHAR(255) NOT NULL,
                       released VARCHAR(255) NOT NULL,
                       runtime VARCHAR(255) NOT NULL,
                       genre VARCHAR(255) NOT NULL,
                       director VARCHAR(255) NOT NULL,
                       writer VARCHAR(255) NOT NULL,
                       actor VARCHAR(255) NOT NULL,
                       plot TEXT,
                       language VARCHAR(255) NOT NULL,
                       country VARCHAR(255) NOT NULL,
                       awards VARCHAR(255),
                       poster VARCHAR(255) NOT NULL,
                       imdb_rating VARCHAR(255) NOT NULL,
                       imdb_votes VARCHAR(255) NOT NULL,
                       type VARCHAR(255) NOT NULL,
                       dvd VARCHAR(255) NOT NULL,
                       box_office VARCHAR(255) NOT NULL,
                       production VARCHAR(255) NOT NULL,
                       added_at TIMESTAMP WITH TIME ZONE,
                       is_deleted BOOLEAN,
                       created_by_id BIGINT,
                       created_at TIMESTAMP WITH TIME ZONE,
                       last_modified_id BIGINT,
                       last_modified_at TIMESTAMP WITH TIME ZONE,
                       deleted_by_id BIGINT,
                       deleted_at TIMESTAMP WITH TIME ZONE,
                       CONSTRAINT pk_movie PRIMARY KEY (movie_id),
                       CONSTRAINT uk_movie_imdbid UNIQUE (imdbid)
);


CREATE TABLE movie_source_ratings (
                                      movie_id BIGINT NOT NULL,
                                      website VARCHAR(255),
                                      rating VARCHAR(255),

                                      CONSTRAINT fk_movie_source_ratings_movie
                                          FOREIGN KEY (movie_id)
                                              REFERENCES movie(movie_id)
);


CREATE TABLE member_rating (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               user_id BIGINT NOT NULL,
                               movie_id BIGINT NOT NULL,
                               rating_value INTEGER NOT NULL,
                               created_by_id BIGINT,
                               created_at TIMESTAMP WITH TIME ZONE,
                               last_modified_id BIGINT,
                               last_modified_at TIMESTAMP WITH TIME ZONE,
                               deleted_by_id BIGINT,
                               deleted_at TIMESTAMP WITH TIME ZONE,
                               CONSTRAINT pk_member_rating PRIMARY KEY (id),

                               CONSTRAINT fk_member_rating_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES users(id),

                               CONSTRAINT fk_member_rating_movie
                                   FOREIGN KEY (movie_id)
                                       REFERENCES movie(movie_id)
);


CREATE INDEX idx_movie_imdbId
    ON movie(imdbid);

CREATE INDEX idx_member_rating_user_id
    ON member_rating(user_id);

CREATE INDEX idx_member_rating_movie_id
    ON member_rating(movie_id);

CREATE INDEX idx_movie_source_ratings_movie_id
    ON movie_source_ratings(movie_id);
